title: "Det Lille Køkken"
locale: "da-DK"
timezone: "Europe/Copenhagen"
words_per_minute: 200
description: "Min samling af opskrifter"
url: "https://detlillekøkken.dk"
baseurl: "" # Lad denne stå tom

# Tema indstillinger
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Prøv 'air' eller 'mint' for et friskt køkken-look

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Side-opbygning
paginate: 5
paginate_path: /page:num/

# Standard indstillinger for indlæg
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
      read_time: true
      share: false
      comments: false

# Standard indstillinger for indlæg

collections:
  opskrifter:
    output: true
    permalink: /opskrifter/:path/

# Opdater også dine defaults, så alle filer i _opskrifter automatisk bruger opskrift-layoutet
defaults:
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "recipe" # Her henviser vi til det layout, vi bygger om lidt
      author_profile: false
      read_time: false
      share: false
      comments: false

# Reading Files
include:
  - .htaccess
  - _pages
