# Logo indstillinger
logo: "/assets/images/logo.png" 
title: "Det Lille Køkken"
locale: "da-DK"
timezone: "Europe/Copenhagen"
words_per_minute: 200
description: "Madinteresse og opskrifter"
url: "https://detlillekøkken.dk"
baseurl: "" # Denne skal stå tom

# Tema indstillinger
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # Prøv 'air' eller 'mint' for et friskt køkken-look

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Side-opbygning
paginate: 5
paginate_path: /page:num/

# Collections
collections:
  opskrifter:
    output: true
    permalink: /:collection/:path/
   # Eller:    permalink: /opskrifter/:path/


# Defaults
defaults:
 # Opskrift - default
  - scope:
      path: ""
      type: "opskrifter"
    values:
      layout: "opskrift" # Her henvises til det layout jeg har bygget
      author_profile: false
      read_time: false
      share: false
      comments: false

 # Indlæg - default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: false
      read_time: true
      share: false
      comments: false


# Læs filer
include:
  - .htaccess
  - _pages
